name: release 

on:
  push:
    paths-ignore:
      - '*.md'
    tags:
      - 'v\d+.\d+*'

jobs:
  release:
    runs-on: [ubuntu-20.04]
    env:
      REPO_PATH: ${{ github.repository }}
      CHART_REGISTRY_URL: chartmuseum.the-collective-group.com
      HELM_REPO_PASSWORD: ${{ secrets.CHART_MUSEUM_PASSWD }}
      HELM_REPO_USERNAME: ${{ secrets.CHART_MUSEUM_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ENV
        run: |
          echo "SERVICE_NAME=${REPO_PATH##*/}" >> $GITHUB_ENV
          echo "TAG=${{ github.event.ref }}" >> $GITHUB_ENV 

      - name: Push helm chart
        run: |
          helm lint ./
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm package ./ --version ${TAG##*/} 
          helm push ./${SERVICE_NAME}-${TAG##*/}.tgz https://${CHART_REGISTRY_URL} 
